version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
          
  # scan Dockerfile for each language agent, in src and tests directories
  - package-ecosystem: docker
    directory: /src/dotnet
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /tests/dotnet
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /src/java
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /tests/java
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /src/nodejs
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /tests/nodejs
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /src/php
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /tests/php
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /src/python
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /tests/python
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /src/ruby
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /tests/ruby
    schedule:
      interval: monthly
