# Copyright New Relic, Inc.
# SPDX-License-Identifier: Apache-2.0
---
    name: Check for modified files
    
    on:
      workflow_call:
        inputs:
          agent-language:
            description: Agent language (dotnet, go, java, node, php, python or ruby)
            type: string
            required: true
        outputs:
          files-changed: 
            value: ${{ jobs.check-modified-files.outputs.files-changed }}
            description: Returns 'true' or 'false'
    
    permissions:
      contents: read
    
    jobs:
      check-modified-files:
        name: Check whether any relevant files were modified
        runs-on: ubuntu-latest
        outputs:
          files-changed: ${{ steps.changes.outputs.files-changed }}
    
        steps:
          - name: Harden Runner
            uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
            with:
              disable-sudo: true
              egress-policy: audit
    
          - name: Checkout code
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
            with:
              persist-credentials: false
              fetch-depth: 0
    
          - name: Check whether files were modified that affect ${{ inputs.agent-language}} build/test/publish
            uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
            id: changes
            with:
              base: ${{ github.ref }}
              filters: |
                files-changed:
                  - '.github/workflows/${{ inputs.agent-language }}.yml'
                  - 'src/${{ inputs.agent-language }}/**'
                  - 'tests/${{ inputs.agent-language }}/**'
    
    