# Copyright New Relic, Inc.
# SPDX-License-Identifier: Apache-2.0
---

name: "PHP Init Container CI"

concurrency:
  group: ${{ github.ref_name || github.ref || github.run_id }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'src/php/**'
      - 'tests/php/**'
      - '.github/workflows/php.yml'
      - '.github/workflows/publish.yml'
      - '.github/workflows/test.yml'
      - '.github/actions/**'
  push:
    paths:
      - 'src/php/**'
      - 'tests/php/**'
      - '.github/workflows/php.yml'
      - '.github/workflows/publish.yml'
      - '.github/workflows/test.yml'
      - '.github/actions/**'
    branches:
      - main
    # Do not run when a tag is created.
    tags-ignore:
      - "**"
  release:
    types:
      - published

env:
  INITCONTAINER_LANGUAGE: php

# Declare default permissions as read only.
permissions: read-all

jobs:
  test:
    if: github.event_name != 'release' || (github.event_name == 'release' && endsWith(github.ref, '_php')) # Skip everything if this isn't PHP
    secrets: inherit
    uses: ./.github/workflows/test.yml
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
        libc: [gnu, musl]
        arch: [amd64, arm64]
        exclude:
          - arch: arm64
            php: '7.2'
          - arch: arm64
            php: '7.3'
          - arch: arm64
            php: '7.4'
    with:
      INITCONTAINER_LANGUAGE: php
      INITCONTAINER_BUILD_ARGS: ${{ matrix.libc }}
      TEST_APP_BUILD_ARGS: ${{ matrix.php-version }}

  publish:
    if: github.event_name == 'release' && endsWith(github.ref, '_php') # Skip everything if this isn't PHP
    needs: test
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    with:
      INITCONTAINER_LANGUAGE: php
      DOCKER_IMAGE_NAME: newrelic/newrelic-node-init
      DOCKER_IMAGE_TAG_SUFFIX: nodejs${{ matrix.node-version }}x
      DOCKER_IMAGE_TAG_IS_DEFAULT_SUFFIX: ${{ matrix.node-version == 22 }}
      BUILD_ARGS: |
        RUNTIME_VERSION=${{ matrix.node-version }}
